HW01: PM2.5 concentration in California 2004 vs 2019
================
VY
2022-09-22

# Upload 2004 and 2019 datasets and look at data

``` r
data04 <- read.csv(file = "/Users/victoriayin/Downloads/ad_viz_plotval_data.csv")
data04 <- data.table(data04)
dim(data04)
```

    ## [1] 19233    20

``` r
head(data04)
```

    ##          Date Source  Site.ID POC Daily.Mean.PM2.5.Concentration    UNITS
    ## 1: 01/01/2004    AQS 60010007   1                           11.0 ug/m3 LC
    ## 2: 01/02/2004    AQS 60010007   1                           12.2 ug/m3 LC
    ## 3: 01/03/2004    AQS 60010007   1                           16.5 ug/m3 LC
    ## 4: 01/04/2004    AQS 60010007   1                           19.5 ug/m3 LC
    ## 5: 01/05/2004    AQS 60010007   1                           11.5 ug/m3 LC
    ## 6: 01/06/2004    AQS 60010007   1                           32.5 ug/m3 LC
    ##    DAILY_AQI_VALUE Site.Name DAILY_OBS_COUNT PERCENT_COMPLETE
    ## 1:              46 Livermore               1              100
    ## 2:              51 Livermore               1              100
    ## 3:              60 Livermore               1              100
    ## 4:              67 Livermore               1              100
    ## 5:              48 Livermore               1              100
    ## 6:              94 Livermore               1              100
    ##    AQS_PARAMETER_CODE                     AQS_PARAMETER_DESC CBSA_CODE
    ## 1:              88502 Acceptable PM2.5 AQI & Speciation Mass     41860
    ## 2:              88502 Acceptable PM2.5 AQI & Speciation Mass     41860
    ## 3:              88502 Acceptable PM2.5 AQI & Speciation Mass     41860
    ## 4:              88502 Acceptable PM2.5 AQI & Speciation Mass     41860
    ## 5:              88502 Acceptable PM2.5 AQI & Speciation Mass     41860
    ## 6:              88502 Acceptable PM2.5 AQI & Speciation Mass     41860
    ##                            CBSA_NAME STATE_CODE      STATE COUNTY_CODE  COUNTY
    ## 1: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 2: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 3: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 4: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 5: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 6: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ##    SITE_LATITUDE SITE_LONGITUDE
    ## 1:      37.68753      -121.7842
    ## 2:      37.68753      -121.7842
    ## 3:      37.68753      -121.7842
    ## 4:      37.68753      -121.7842
    ## 5:      37.68753      -121.7842
    ## 6:      37.68753      -121.7842

``` r
tail(data04)
```

    ##          Date Source  Site.ID POC Daily.Mean.PM2.5.Concentration    UNITS
    ## 1: 12/14/2004    AQS 61131003   1                             11 ug/m3 LC
    ## 2: 12/17/2004    AQS 61131003   1                             16 ug/m3 LC
    ## 3: 12/20/2004    AQS 61131003   1                             17 ug/m3 LC
    ## 4: 12/23/2004    AQS 61131003   1                              9 ug/m3 LC
    ## 5: 12/26/2004    AQS 61131003   1                             24 ug/m3 LC
    ## 6: 12/29/2004    AQS 61131003   1                              9 ug/m3 LC
    ##    DAILY_AQI_VALUE            Site.Name DAILY_OBS_COUNT PERCENT_COMPLETE
    ## 1:              46 Woodland-Gibson Road               1              100
    ## 2:              59 Woodland-Gibson Road               1              100
    ## 3:              61 Woodland-Gibson Road               1              100
    ## 4:              38 Woodland-Gibson Road               1              100
    ## 5:              76 Woodland-Gibson Road               1              100
    ## 6:              38 Woodland-Gibson Road               1              100
    ##    AQS_PARAMETER_CODE       AQS_PARAMETER_DESC CBSA_CODE
    ## 1:              88101 PM2.5 - Local Conditions     40900
    ## 2:              88101 PM2.5 - Local Conditions     40900
    ## 3:              88101 PM2.5 - Local Conditions     40900
    ## 4:              88101 PM2.5 - Local Conditions     40900
    ## 5:              88101 PM2.5 - Local Conditions     40900
    ## 6:              88101 PM2.5 - Local Conditions     40900
    ##                                  CBSA_NAME STATE_CODE      STATE COUNTY_CODE
    ## 1: Sacramento--Roseville--Arden-Arcade, CA          6 California         113
    ## 2: Sacramento--Roseville--Arden-Arcade, CA          6 California         113
    ## 3: Sacramento--Roseville--Arden-Arcade, CA          6 California         113
    ## 4: Sacramento--Roseville--Arden-Arcade, CA          6 California         113
    ## 5: Sacramento--Roseville--Arden-Arcade, CA          6 California         113
    ## 6: Sacramento--Roseville--Arden-Arcade, CA          6 California         113
    ##    COUNTY SITE_LATITUDE SITE_LONGITUDE
    ## 1:   Yolo      38.66121      -121.7327
    ## 2:   Yolo      38.66121      -121.7327
    ## 3:   Yolo      38.66121      -121.7327
    ## 4:   Yolo      38.66121      -121.7327
    ## 5:   Yolo      38.66121      -121.7327
    ## 6:   Yolo      38.66121      -121.7327

``` r
str(data04)
```

    ## Classes 'data.table' and 'data.frame':   19233 obs. of  20 variables:
    ##  $ Date                          : chr  "01/01/2004" "01/02/2004" "01/03/2004" "01/04/2004" ...
    ##  $ Source                        : chr  "AQS" "AQS" "AQS" "AQS" ...
    ##  $ Site.ID                       : int  60010007 60010007 60010007 60010007 60010007 60010007 60010007 60010007 60010007 60010007 ...
    ##  $ POC                           : int  1 1 1 1 1 1 1 1 1 1 ...
    ##  $ Daily.Mean.PM2.5.Concentration: num  11 12.2 16.5 19.5 11.5 32.5 15.5 29.9 21 15.7 ...
    ##  $ UNITS                         : chr  "ug/m3 LC" "ug/m3 LC" "ug/m3 LC" "ug/m3 LC" ...
    ##  $ DAILY_AQI_VALUE               : int  46 51 60 67 48 94 58 88 70 59 ...
    ##  $ Site.Name                     : chr  "Livermore" "Livermore" "Livermore" "Livermore" ...
    ##  $ DAILY_OBS_COUNT               : int  1 1 1 1 1 1 1 1 1 1 ...
    ##  $ PERCENT_COMPLETE              : num  100 100 100 100 100 100 100 100 100 100 ...
    ##  $ AQS_PARAMETER_CODE            : int  88502 88502 88502 88502 88502 88502 88502 88502 88502 88101 ...
    ##  $ AQS_PARAMETER_DESC            : chr  "Acceptable PM2.5 AQI & Speciation Mass" "Acceptable PM2.5 AQI & Speciation Mass" "Acceptable PM2.5 AQI & Speciation Mass" "Acceptable PM2.5 AQI & Speciation Mass" ...
    ##  $ CBSA_CODE                     : int  41860 41860 41860 41860 41860 41860 41860 41860 41860 41860 ...
    ##  $ CBSA_NAME                     : chr  "San Francisco-Oakland-Hayward, CA" "San Francisco-Oakland-Hayward, CA" "San Francisco-Oakland-Hayward, CA" "San Francisco-Oakland-Hayward, CA" ...
    ##  $ STATE_CODE                    : int  6 6 6 6 6 6 6 6 6 6 ...
    ##  $ STATE                         : chr  "California" "California" "California" "California" ...
    ##  $ COUNTY_CODE                   : int  1 1 1 1 1 1 1 1 1 1 ...
    ##  $ COUNTY                        : chr  "Alameda" "Alameda" "Alameda" "Alameda" ...
    ##  $ SITE_LATITUDE                 : num  37.7 37.7 37.7 37.7 37.7 ...
    ##  $ SITE_LONGITUDE                : num  -122 -122 -122 -122 -122 ...
    ##  - attr(*, ".internal.selfref")=<externalptr>

``` r
data19 <- read.csv(file = "/Users/victoriayin/Downloads/ad_viz_plotval_data (1).csv")
data19 <- data.table(data19)
dim(data19)
```

    ## [1] 53156    20

``` r
head(data19)
```

    ##          Date Source  Site.ID POC Daily.Mean.PM2.5.Concentration    UNITS
    ## 1: 01/01/2019    AQS 60010007   3                            5.7 ug/m3 LC
    ## 2: 01/02/2019    AQS 60010007   3                           11.9 ug/m3 LC
    ## 3: 01/03/2019    AQS 60010007   3                           20.1 ug/m3 LC
    ## 4: 01/04/2019    AQS 60010007   3                           28.8 ug/m3 LC
    ## 5: 01/05/2019    AQS 60010007   3                           11.2 ug/m3 LC
    ## 6: 01/06/2019    AQS 60010007   3                            2.7 ug/m3 LC
    ##    DAILY_AQI_VALUE Site.Name DAILY_OBS_COUNT PERCENT_COMPLETE
    ## 1:              24 Livermore               1              100
    ## 2:              50 Livermore               1              100
    ## 3:              68 Livermore               1              100
    ## 4:              86 Livermore               1              100
    ## 5:              47 Livermore               1              100
    ## 6:              11 Livermore               1              100
    ##    AQS_PARAMETER_CODE       AQS_PARAMETER_DESC CBSA_CODE
    ## 1:              88101 PM2.5 - Local Conditions     41860
    ## 2:              88101 PM2.5 - Local Conditions     41860
    ## 3:              88101 PM2.5 - Local Conditions     41860
    ## 4:              88101 PM2.5 - Local Conditions     41860
    ## 5:              88101 PM2.5 - Local Conditions     41860
    ## 6:              88101 PM2.5 - Local Conditions     41860
    ##                            CBSA_NAME STATE_CODE      STATE COUNTY_CODE  COUNTY
    ## 1: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 2: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 3: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 4: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 5: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 6: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ##    SITE_LATITUDE SITE_LONGITUDE
    ## 1:      37.68753      -121.7842
    ## 2:      37.68753      -121.7842
    ## 3:      37.68753      -121.7842
    ## 4:      37.68753      -121.7842
    ## 5:      37.68753      -121.7842
    ## 6:      37.68753      -121.7842

``` r
tail(data19)
```

    ##          Date Source  Site.ID POC Daily.Mean.PM2.5.Concentration    UNITS
    ## 1: 11/11/2019    AQS 61131003   1                           13.5 ug/m3 LC
    ## 2: 11/17/2019    AQS 61131003   1                           18.1 ug/m3 LC
    ## 3: 11/29/2019    AQS 61131003   1                           12.5 ug/m3 LC
    ## 4: 12/17/2019    AQS 61131003   1                           23.8 ug/m3 LC
    ## 5: 12/23/2019    AQS 61131003   1                            1.0 ug/m3 LC
    ## 6: 12/29/2019    AQS 61131003   1                            9.1 ug/m3 LC
    ##    DAILY_AQI_VALUE            Site.Name DAILY_OBS_COUNT PERCENT_COMPLETE
    ## 1:              54 Woodland-Gibson Road               1              100
    ## 2:              64 Woodland-Gibson Road               1              100
    ## 3:              52 Woodland-Gibson Road               1              100
    ## 4:              76 Woodland-Gibson Road               1              100
    ## 5:               4 Woodland-Gibson Road               1              100
    ## 6:              38 Woodland-Gibson Road               1              100
    ##    AQS_PARAMETER_CODE       AQS_PARAMETER_DESC CBSA_CODE
    ## 1:              88101 PM2.5 - Local Conditions     40900
    ## 2:              88101 PM2.5 - Local Conditions     40900
    ## 3:              88101 PM2.5 - Local Conditions     40900
    ## 4:              88101 PM2.5 - Local Conditions     40900
    ## 5:              88101 PM2.5 - Local Conditions     40900
    ## 6:              88101 PM2.5 - Local Conditions     40900
    ##                                  CBSA_NAME STATE_CODE      STATE COUNTY_CODE
    ## 1: Sacramento--Roseville--Arden-Arcade, CA          6 California         113
    ## 2: Sacramento--Roseville--Arden-Arcade, CA          6 California         113
    ## 3: Sacramento--Roseville--Arden-Arcade, CA          6 California         113
    ## 4: Sacramento--Roseville--Arden-Arcade, CA          6 California         113
    ## 5: Sacramento--Roseville--Arden-Arcade, CA          6 California         113
    ## 6: Sacramento--Roseville--Arden-Arcade, CA          6 California         113
    ##    COUNTY SITE_LATITUDE SITE_LONGITUDE
    ## 1:   Yolo      38.66121      -121.7327
    ## 2:   Yolo      38.66121      -121.7327
    ## 3:   Yolo      38.66121      -121.7327
    ## 4:   Yolo      38.66121      -121.7327
    ## 5:   Yolo      38.66121      -121.7327
    ## 6:   Yolo      38.66121      -121.7327

``` r
str(data19)
```

    ## Classes 'data.table' and 'data.frame':   53156 obs. of  20 variables:
    ##  $ Date                          : chr  "01/01/2019" "01/02/2019" "01/03/2019" "01/04/2019" ...
    ##  $ Source                        : chr  "AQS" "AQS" "AQS" "AQS" ...
    ##  $ Site.ID                       : int  60010007 60010007 60010007 60010007 60010007 60010007 60010007 60010007 60010007 60010007 ...
    ##  $ POC                           : int  3 3 3 3 3 3 3 3 3 3 ...
    ##  $ Daily.Mean.PM2.5.Concentration: num  5.7 11.9 20.1 28.8 11.2 2.7 2.8 7 3.1 7.1 ...
    ##  $ UNITS                         : chr  "ug/m3 LC" "ug/m3 LC" "ug/m3 LC" "ug/m3 LC" ...
    ##  $ DAILY_AQI_VALUE               : int  24 50 68 86 47 11 12 29 13 30 ...
    ##  $ Site.Name                     : chr  "Livermore" "Livermore" "Livermore" "Livermore" ...
    ##  $ DAILY_OBS_COUNT               : int  1 1 1 1 1 1 1 1 1 1 ...
    ##  $ PERCENT_COMPLETE              : num  100 100 100 100 100 100 100 100 100 100 ...
    ##  $ AQS_PARAMETER_CODE            : int  88101 88101 88101 88101 88101 88101 88101 88101 88101 88101 ...
    ##  $ AQS_PARAMETER_DESC            : chr  "PM2.5 - Local Conditions" "PM2.5 - Local Conditions" "PM2.5 - Local Conditions" "PM2.5 - Local Conditions" ...
    ##  $ CBSA_CODE                     : int  41860 41860 41860 41860 41860 41860 41860 41860 41860 41860 ...
    ##  $ CBSA_NAME                     : chr  "San Francisco-Oakland-Hayward, CA" "San Francisco-Oakland-Hayward, CA" "San Francisco-Oakland-Hayward, CA" "San Francisco-Oakland-Hayward, CA" ...
    ##  $ STATE_CODE                    : int  6 6 6 6 6 6 6 6 6 6 ...
    ##  $ STATE                         : chr  "California" "California" "California" "California" ...
    ##  $ COUNTY_CODE                   : int  1 1 1 1 1 1 1 1 1 1 ...
    ##  $ COUNTY                        : chr  "Alameda" "Alameda" "Alameda" "Alameda" ...
    ##  $ SITE_LATITUDE                 : num  37.7 37.7 37.7 37.7 37.7 ...
    ##  $ SITE_LONGITUDE                : num  -122 -122 -122 -122 -122 ...
    ##  - attr(*, ".internal.selfref")=<externalptr>

There do not appear to be any data issues at first glance. Each dataset
contains the same 20 variables. There were 19233 observations in 2004
and 53156 observations in 2019.

# Merge datasets

``` r
alldata <- bind_rows(data04, data19, .id= "id")
alldata <- alldata %>%
            mutate(id = recode(id, "1" = "2004", "2" = "2019"))
```

# Add date column for identification and change names of columns (for easier reference)

``` r
alldata <- alldata[ , dateclean := as.Date(as.character(Date), "%m/%d/%Y")]
```

    ## Warning in `[.data.table`(alldata, , `:=`(dateclean,
    ## as.Date(as.character(Date), : Invalid .internal.selfref detected and fixed by
    ## taking a (shallow) copy of the data.table so that := can add this new column
    ## by reference. At an earlier point, this data.table has been copied by R (or
    ## was created manually using structure() or similar). Avoid names<- and attr<-
    ## which in R currently (and oddly) may copy the whole data.table. Use set* syntax
    ## instead to avoid copying: ?set, ?setnames and ?setattr. If this message doesn't
    ## help, please report your use case to the data.table issue tracker so the root
    ## cause can be fixed or this message improved.

``` r
alldata1 <- rename (alldata, PM2.5 = Daily.Mean.PM2.5.Concentration, lat = SITE_LATITUDE, lng = SITE_LONGITUDE, AQI = DAILY_AQI_VALUE)
head(alldata1)
```

    ##      id       Date Source  Site.ID POC PM2.5    UNITS AQI Site.Name
    ## 1: 2004 01/01/2004    AQS 60010007   1  11.0 ug/m3 LC  46 Livermore
    ## 2: 2004 01/02/2004    AQS 60010007   1  12.2 ug/m3 LC  51 Livermore
    ## 3: 2004 01/03/2004    AQS 60010007   1  16.5 ug/m3 LC  60 Livermore
    ## 4: 2004 01/04/2004    AQS 60010007   1  19.5 ug/m3 LC  67 Livermore
    ## 5: 2004 01/05/2004    AQS 60010007   1  11.5 ug/m3 LC  48 Livermore
    ## 6: 2004 01/06/2004    AQS 60010007   1  32.5 ug/m3 LC  94 Livermore
    ##    DAILY_OBS_COUNT PERCENT_COMPLETE AQS_PARAMETER_CODE
    ## 1:               1              100              88502
    ## 2:               1              100              88502
    ## 3:               1              100              88502
    ## 4:               1              100              88502
    ## 5:               1              100              88502
    ## 6:               1              100              88502
    ##                        AQS_PARAMETER_DESC CBSA_CODE
    ## 1: Acceptable PM2.5 AQI & Speciation Mass     41860
    ## 2: Acceptable PM2.5 AQI & Speciation Mass     41860
    ## 3: Acceptable PM2.5 AQI & Speciation Mass     41860
    ## 4: Acceptable PM2.5 AQI & Speciation Mass     41860
    ## 5: Acceptable PM2.5 AQI & Speciation Mass     41860
    ## 6: Acceptable PM2.5 AQI & Speciation Mass     41860
    ##                            CBSA_NAME STATE_CODE      STATE COUNTY_CODE  COUNTY
    ## 1: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 2: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 3: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 4: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 5: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ## 6: San Francisco-Oakland-Hayward, CA          6 California           1 Alameda
    ##         lat       lng  dateclean
    ## 1: 37.68753 -121.7842 2004-01-01
    ## 2: 37.68753 -121.7842 2004-01-02
    ## 3: 37.68753 -121.7842 2004-01-03
    ## 4: 37.68753 -121.7842 2004-01-04
    ## 5: 37.68753 -121.7842 2004-01-05
    ## 6: 37.68753 -121.7842 2004-01-06

# Create a basic map in leaflet() that shows the locations of the sites (make sure to use different colors for each year). Summarize the spatial distribution of the monitoring sites.

``` r
site.pal <- colorFactor("RdYlBu", domain=alldata1$id)
site.pal
```

    ## function (x) 
    ## {
    ##     if (length(x) == 0 || all(is.na(x))) {
    ##         return(rep.int(na.color, length(x)))
    ##     }
    ##     lvls <- getLevels(domain, x, lvls, ordered)
    ##     pf <- safePaletteFunc(palette, na.color, alpha, nlevels = length(lvls) * 
    ##         ifelse(reverse, -1, 1))
    ##     origNa <- is.na(x)
    ##     x <- match(as.character(x), lvls)
    ##     if (any(is.na(x) != origNa)) {
    ##         warning("Some values were outside the color scale and will be treated as NA")
    ##     }
    ##     scaled <- scales::rescale(as.integer(x), from = c(1, length(lvls)))
    ##     if (any(scaled < 0 | scaled > 1, na.rm = TRUE)) {
    ##         warning("Some values were outside the color scale and will be treated as NA")
    ##     }
    ##     if (reverse) {
    ##         scaled <- 1 - scaled
    ##     }
    ##     pf(scaled)
    ## }
    ## <bytecode: 0x7fc1c93a1a18>
    ## <environment: 0x7fc1c939c438>
    ## attr(,"colorType")
    ## [1] "factor"
    ## attr(,"colorArgs")
    ## attr(,"colorArgs")$na.color
    ## [1] "#808080"

``` r
sitemap <- leaflet(alldata1) %>%
  addProviderTiles('CartoDB.Positron') %>%
  addCircles(
    lng =~lng, lat =~lat,
     color = ~site.pal(alldata1$id),
     fillOpacity = 0.5, radius = 500
  ) %>%
  addLegend('bottomleft', pal=site.pal, values=~alldata1$id, title = "Spatial map of site location by year", opacity=1, labels = c("2004", "2009"))
sitemap
```

![](HW01_files/figure-gfm/spatial%20map-1.png)<!-- --> It appears that a
lot more sites were added all over California, especially central
California. There are highest density of sites around LA and SF.

# Check for any missing or implausible values of PM2.5 in the combined dataset (ie incomplete county data). Explore the proportions of each and provide a summary of any temporal patterns you see in these observations.

``` r
summary(alldata1$PM2.5)
```

    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  -2.200   4.400   7.200   9.172  11.300 251.000

``` r
ggplot(alldata1, aes(x=PM2.5)) + geom_histogram(binwidth=0.1)
```

![](HW01_files/figure-gfm/examining%20PM2.5%20data-1.png)<!-- -->

``` r
alldata2 <- alldata1[order(PM2.5)]
head(alldata2)
```

    ##      id       Date Source  Site.ID POC PM2.5    UNITS AQI
    ## 1: 2019 03/16/2019    AQS 60130002   3  -2.2 ug/m3 LC   0
    ## 2: 2019 03/02/2019    AQS 60611004   3  -2.0 ug/m3 LC   0
    ## 3: 2019 03/05/2019    AQS 60611004   3  -2.0 ug/m3 LC   0
    ## 4: 2019 03/06/2019    AQS 60611004   3  -2.0 ug/m3 LC   0
    ## 5: 2019 03/07/2019    AQS 60611004   3  -2.0 ug/m3 LC   0
    ## 6: 2019 03/08/2019    AQS 60611004   3  -2.0 ug/m3 LC   0
    ##                   Site.Name DAILY_OBS_COUNT PERCENT_COMPLETE AQS_PARAMETER_CODE
    ## 1:                  Concord               1              100              88101
    ## 2: Tahoe City-Fairway Drive               1              100              88502
    ## 3: Tahoe City-Fairway Drive               1              100              88502
    ## 4: Tahoe City-Fairway Drive               1              100              88502
    ## 5: Tahoe City-Fairway Drive               1              100              88502
    ## 6: Tahoe City-Fairway Drive               1              100              88502
    ##                        AQS_PARAMETER_DESC CBSA_CODE
    ## 1:               PM2.5 - Local Conditions     41860
    ## 2: Acceptable PM2.5 AQI & Speciation Mass     40900
    ## 3: Acceptable PM2.5 AQI & Speciation Mass     40900
    ## 4: Acceptable PM2.5 AQI & Speciation Mass     40900
    ## 5: Acceptable PM2.5 AQI & Speciation Mass     40900
    ## 6: Acceptable PM2.5 AQI & Speciation Mass     40900
    ##                                  CBSA_NAME STATE_CODE      STATE COUNTY_CODE
    ## 1:       San Francisco-Oakland-Hayward, CA          6 California          13
    ## 2: Sacramento--Roseville--Arden-Arcade, CA          6 California          61
    ## 3: Sacramento--Roseville--Arden-Arcade, CA          6 California          61
    ## 4: Sacramento--Roseville--Arden-Arcade, CA          6 California          61
    ## 5: Sacramento--Roseville--Arden-Arcade, CA          6 California          61
    ## 6: Sacramento--Roseville--Arden-Arcade, CA          6 California          61
    ##          COUNTY      lat       lng  dateclean
    ## 1: Contra Costa 37.93601 -122.0262 2019-03-16
    ## 2:       Placer 39.16602 -120.1488 2019-03-02
    ## 3:       Placer 39.16602 -120.1488 2019-03-05
    ## 4:       Placer 39.16602 -120.1488 2019-03-06
    ## 5:       Placer 39.16602 -120.1488 2019-03-07
    ## 6:       Placer 39.16602 -120.1488 2019-03-08

``` r
tail(alldata2)
```

    ##      id       Date Source  Site.ID POC PM2.5    UNITS AQI
    ## 1: 2004 07/15/2004    AQS 60431001   3 110.4 ug/m3 LC 179
    ## 2: 2019 10/11/2019    AQS 60371201   3 120.9 ug/m3 LC 185
    ## 3: 2004 07/21/2004    AQS 60431001   3 122.5 ug/m3 LC 186
    ## 4: 2004 07/20/2004    AQS 60431001   3 148.4 ug/m3 LC 199
    ## 5: 2004 07/19/2004    AQS 60431001   3 170.4 ug/m3 LC 221
    ## 6: 2004 07/18/2004    AQS 60431001   3 251.0 ug/m3 LC 301
    ##                                     Site.Name DAILY_OBS_COUNT PERCENT_COMPLETE
    ## 1: Yosemite NP-Yosemite Village Vistor Center               1              100
    ## 2:                                     Reseda               1              100
    ## 3: Yosemite NP-Yosemite Village Vistor Center               1              100
    ## 4: Yosemite NP-Yosemite Village Vistor Center               1              100
    ## 5: Yosemite NP-Yosemite Village Vistor Center               1              100
    ## 6: Yosemite NP-Yosemite Village Vistor Center               1              100
    ##    AQS_PARAMETER_CODE                     AQS_PARAMETER_DESC CBSA_CODE
    ## 1:              88502 Acceptable PM2.5 AQI & Speciation Mass        NA
    ## 2:              88502 Acceptable PM2.5 AQI & Speciation Mass     31080
    ## 3:              88502 Acceptable PM2.5 AQI & Speciation Mass        NA
    ## 4:              88502 Acceptable PM2.5 AQI & Speciation Mass        NA
    ## 5:              88502 Acceptable PM2.5 AQI & Speciation Mass        NA
    ## 6:              88502 Acceptable PM2.5 AQI & Speciation Mass        NA
    ##                             CBSA_NAME STATE_CODE      STATE COUNTY_CODE
    ## 1:                                             6 California          43
    ## 2: Los Angeles-Long Beach-Anaheim, CA          6 California          37
    ## 3:                                             6 California          43
    ## 4:                                             6 California          43
    ## 5:                                             6 California          43
    ## 6:                                             6 California          43
    ##         COUNTY      lat       lng  dateclean
    ## 1:    Mariposa 37.74871 -119.5871 2004-07-15
    ## 2: Los Angeles 34.19925 -118.5328 2019-10-11
    ## 3:    Mariposa 37.74871 -119.5871 2004-07-21
    ## 4:    Mariposa 37.74871 -119.5871 2004-07-20
    ## 5:    Mariposa 37.74871 -119.5871 2004-07-19
    ## 6:    Mariposa 37.74871 -119.5871 2004-07-18

``` r
alldata1[PM2.5<0] %>% nrow()
```

    ## [1] 283

``` r
alldata1[is.na(PM2.5)] %>% nrow()
```

    ## [1] 0

``` r
alldata1[is.na(COUNTY)] %>% nrow()
```

    ## [1] 0

``` r
alldata1[is.na(Site.ID)] %>% nrow()
```

    ## [1] 0

``` r
alldata1[is.na(Site.Name)] %>% nrow()
```

    ## [1] 0

``` r
alldata1 <- alldata1[PM2.5>0]
sum04 <- alldata1[id=="2004", PM2.5] %>% summary(PM2.5)
sum19 <- alldata1[id=="2019", PM2.5] %>% summary(PM2.5)
summary <- bind_rows(sum04, sum19, .id = "year")
summary
```

    ## # A tibble: 2 × 7
    ##   year  Min.    `1st Qu.` Median  Mean      `3rd Qu.` Max.   
    ##   <chr> <table> <table>   <table> <table>   <table>   <table>
    ## 1 1     0.1     6.0       10.1    13.138515 16.3      251.0  
    ## 2 2     0.1     4.1        6.5     7.796663 10.0      120.9

No data on county were missing. One Site.Name is missing for LA County
(but not NA), however correlates with a single Site.ID (60371601) so it
does not cause inaccuracies in the data analysis. There were negative
values comprising 283(0.4%) of the overall data (deleted). For PM2.5,
there were no NA values, no 9999 values, no weird modes (when looking at
the histogram below), but there is a large positive skew. Max was 251.
It does seem like 251 is a feasible measurement, considering there was a
fire in that region that day.
<https://www.airnow.gov/aqi/aqi-basics/extremely-high-levels-of-pm25/>
<https://www.sfgate.com/bayarea/article/CALIFORNIA-Yosemite-fire-spreads-shuts-trails-2741685.php>

# Explore the main question of interest at three different spatial levels (state, county, Los Angeles). Create exploratory plots (e.g. boxplots, histograms, line plots) and summary statistics that best suit each level of data. Be sure to write up explanations of what you observe in these data.

``` r
histostate <- ggplot(alldata1, aes(x=PM2.5, color=id)) +
  geom_histogram(binwidth=0.1, fill="white", position="dodge") +
  theme(legend.position="right")
histostate
```

![](HW01_files/figure-gfm/changes%20in%20PM2.5%20at%203%20levels-1.png)<!-- -->

``` r
county_averages <- 
  alldata1[ , 
    countyPM2.5 := mean(PM2.5, na.rm=T),
   by = c("COUNTY", "id")]
ggplot(data=county_averages, aes(x=id, y=countyPM2.5, group=COUNTY, color=COUNTY)) +
  geom_line()+
  geom_point() +
  theme(legend.position="right")
```

![](HW01_files/figure-gfm/changes%20in%20PM2.5%20at%203%20levels-2.png)<!-- -->

``` r
countymeanyear <- county_averages[ , c("id", "COUNTY", "countyPM2.5")]

countymeanyear1 <- countymeanyear[!duplicated(countyPM2.5)]
countymeanyear1.wide <- pivot_wider(countymeanyear1, names_from = COUNTY, values_from = countyPM2.5) 
countymeanyear1.wide
```

    ## # A tibble: 2 × 52
    ##   id    Alameda Butte Calaveras Colusa Contra C…¹ Del N…² El Do…³ Fresno Humbo…⁴
    ##   <chr>   <dbl> <dbl>     <dbl>  <dbl>      <dbl>   <dbl>   <dbl>  <dbl>   <dbl>
    ## 1 2004    11.0  10.1       7.61  10.0       12.8     3.44    3.52  15.5     8.22
    ## 2 2019     7.34  7.01      5.46   6.63       7.20    4.93    2.75   8.55    6.79
    ## # … with 42 more variables: Imperial <dbl>, Inyo <dbl>, Kern <dbl>,
    ## #   Kings <dbl>, Lake <dbl>, `Los Angeles` <dbl>, Marin <dbl>, Mariposa <dbl>,
    ## #   Mendocino <dbl>, Merced <dbl>, Mono <dbl>, Monterey <dbl>, Nevada <dbl>,
    ## #   Orange <dbl>, Placer <dbl>, Plumas <dbl>, Riverside <dbl>,
    ## #   Sacramento <dbl>, `San Benito` <dbl>, `San Bernardino` <dbl>,
    ## #   `San Diego` <dbl>, `San Francisco` <dbl>, `San Joaquin` <dbl>,
    ## #   `San Luis Obispo` <dbl>, `San Mateo` <dbl>, `Santa Barbara` <dbl>, …

``` r
LA_averages <-
  alldata1[COUNTY=="Los Angeles"]
LA_averages <- LA_averages[ , meanPM2.5 := mean(PM2.5, na.rm=T), by = c("Site.ID", "id")]
ggplot(data=LA_averages, aes(x=id, y=meanPM2.5, group=Site.ID, color=Site.Name)) +
  geom_line()+
  geom_point() 
```

![](HW01_files/figure-gfm/changes%20in%20PM2.5%20at%203%20levels-3.png)<!-- -->

``` r
LAmeanyear <- LA_averages[ , c("id", "Site.ID", "Site.Name", "meanPM2.5")]
LAmeanyear <- LAmeanyear[!duplicated(meanPM2.5)]
LAmeanyear.wide <- pivot_wider(LAmeanyear, names_from = "id", values_from = meanPM2.5)
LAmeanyear.wide
```

    ## # A tibble: 16 × 4
    ##     Site.ID Site.Name                        `2004` `2019`
    ##       <int> <chr>                             <dbl>  <dbl>
    ##  1 60370002 "Azusa"                           18.4    9.69
    ##  2 60371002 "Burbank"                         19.2   NA   
    ##  3 60371103 "Los Angeles-North Main Street"   20.1   11.7 
    ##  4 60371201 "Reseda"                          15.6   11.2 
    ##  5 60371301 "Lynwood"                         18.5   NA   
    ##  6 60371601 ""                                19.9   NA   
    ##  7 60372005 "Pasadena"                        16.6    8.99
    ##  8 60374002 "Long Beach (North)"              17.6    9.02
    ##  9 60374004 "Long Beach (South)"              16.6    9.94
    ## 10 60379033 "Lancaster-Division Street"        8.50   6.21
    ## 11 60379034 "Lebec"                            4.14   3.15
    ## 12 60370016 "Glendora"                        NA     11.9 
    ## 13 60371302 "Compton"                         NA     11.0 
    ## 14 60371602 "Pico Rivera #2"                  NA     10.4 
    ## 15 60374008 "Long Beach-Route 710 Near Road"  NA     12.1 
    ## 16 60376012 "Santa Clarita"                   NA      6.74

# Observations

## State Level

It appears that PM2.5 levels were lower in 2019 than in 2004. The 1st
quartile, median, mean, 3rd quartile, and max PM2.5 levels were all
lower in 2019 when compared to 2004. The histogram shows that the
distribution of PM2.5 levels in 2004 was more right-shifted than the
distribution of PM2.5 in 2019.

## County Level

The line plot shows that the majority of counties experienced a decrease
in PM2.5 levels from 2004 to 2019. Looking at the table of the mean
PM2.5 by county and year, it appears only the counties of Del Norte,
Inyo, Marin, Mono, San Benito, Siskiyou, and Trinity experienced an
increase in average PM2.5 levels, however most of these increases were
relatively small. 2004 data from Glenn and Madera counties were missing,
therefore a comparison could not be made between 2004 and 2019.

## Los Angeles Level

While many sites were missing data from both 2004 and 2019, all sites
with complete information in LA county experienced a decrease in mean
PM2.5 in 2019 vs 2004. The line plot also reflects this, and the new
sites appear to have relatively lower levels of PM2.5 than most sites in
2004.
